"use client";

import { useMemo, useRef, useState } from "react";
import { Boxes, Download, Play, Puzzle, Trash2, Upload, X } from "lucide-react";
import { applyExtensionFoundation, dispatchExtensionSkill, installExtension, loadExtensions, parseExtensionManifest, uninstallExtension, type ExtensionManifest } from "@/lib/extensions";
import { LocalProjectRepository } from "@/lib/storage";
import { downloadText } from "@/lib/export";

export function ExtensionsPanel(){
  const repository=useMemo(()=>new LocalProjectRepository(),[]),fileRef=useRef<HTMLInputElement>(null);
  const [open,setOpen]=useState(false),[extensions,setExtensions]=useState<ExtensionManifest[]>(loadExtensions),[error,setError]=useState("");
  const importFile=async(file?:File)=>{if(!file)return;try{if(file.size>256_000)throw new Error("Extension manifest exceeds 256 KB.");const extension=parseExtensionManifest(await file.text());setExtensions(installExtension(extension));setError("");}catch(cause){setError(cause instanceof Error?cause.message:String(cause));}finally{if(fileRef.current)fileRef.current.value="";}};
  const applyFoundation=async(extension:ExtensionManifest,foundation:NonNullable<ExtensionManifest["foundations"]>[number])=>{const project=await repository.load();if(!project)return;await repository.save(applyExtensionFoundation(project,extension,foundation));window.location.reload();};
  if(!open)return <button className="fixed bottom-24 right-[115px] z-[87] flex h-9 items-center gap-2 rounded-lg border border-[#343a45] bg-[#14171d]/95 px-3 text-[11px] text-[#d8dce3] shadow-xl backdrop-blur hover:bg-[#1b1f27]" onClick={()=>setOpen(true)}><Puzzle size={13}/> Extensions</button>;
  return <div className="fixed inset-0 z-[84] grid place-items-center bg-black/65 p-6 backdrop-blur-sm"><div className="flex h-[min(760px,calc(100vh-3rem))] w-[min(1050px,calc(100vw-3rem))] flex-col overflow-hidden rounded-xl border border-[#343a45] bg-[#0d1015] shadow-2xl">
    <div className="flex h-12 items-center gap-2 border-b border-[#292e36] px-3"><Puzzle size={14} className="text-[#8d99ff]"/><div className="flex-1"><div className="text-[12px] font-semibold">Declarative extension ecosystem</div><div className="text-[9px] text-[#6e7784]">Foundations + AI skills. v1 intentionally executes no third-party JavaScript.</div></div><button className="tool-button primary" onClick={()=>fileRef.current?.click()}><Upload size={11}/> Install manifest</button><input ref={fileRef} type="file" accept=".json,application/json" className="hidden" onChange={(event)=>void importFile(event.target.files?.[0])}/><button className="tool-button" onClick={()=>setOpen(false)}><X size={12}/></button></div>
    {error&&<div className="border-b border-[#4b292e] bg-[#211215] px-4 py-2 text-[10px] text-[#e78c96]">{error}</div>}
    <div className="min-h-0 flex-1 overflow-auto p-4">{extensions.length===0?<div className="grid h-full place-items-center"><div className="max-w-md text-center text-[10px] leading-5 text-[#68717d]"><Boxes size={28} className="mx-auto mb-3 text-[#4f5865]"/>No extensions installed. Import a declarative v1 manifest; an example ships in <code>examples/extensions/editorial-saas.json</code>.</div></div>:<div className="space-y-4">{extensions.map((extension)=><article key={extension.id} className="rounded-xl border border-[#292e36] bg-[#111419] p-4"><div className="flex items-start gap-3"><div className="min-w-0 flex-1"><div className="text-[12px] font-semibold">{extension.name} <span className="ml-1 text-[9px] font-normal text-[#68717d]">v{extension.version}</span></div><div className="mt-1 text-[10px] leading-4 text-[#858e9b]">{extension.description}</div><div className="mt-1 font-mono text-[8px] text-[#59626f]">{extension.id}{extension.author?` · ${extension.author}`:""}</div></div><button className="tool-button" onClick={()=>downloadText(`${extension.id}.extension.json`,JSON.stringify(extension,null,2),"application/json")}><Download size={11}/></button><button className="tool-button danger" onClick={()=>setExtensions(uninstallExtension(extension.id))}><Trash2 size={11}/></button></div>
          {!!extension.foundations?.length&&<div className="mt-4"><div className="panel-label">Foundations</div><div className="grid grid-cols-2 gap-2">{extension.foundations.map((foundation)=><div key={foundation.id} className="rounded-lg border border-[#292e36] p-3"><div className="text-[10px] font-semibold">{foundation.name}</div><div className="mt-1 text-[9px] leading-4 text-[#68717d]">{foundation.description}</div><button className="tool-button primary mt-2 w-full" onClick={()=>void applyFoundation(extension,foundation)}>Apply foundation</button></div>)}</div></div>}
          {!!extension.skills?.length&&<div className="mt-4"><div className="panel-label">AI skills</div><div className="grid grid-cols-2 gap-2">{extension.skills.map((skill)=><div key={skill.id} className="rounded-lg border border-[#292e36] p-3"><div className="flex items-center justify-between"><span className="text-[10px] font-semibold">{skill.name}</span><span className="text-[8px] uppercase text-[#68717d]">{skill.scope}</span></div><div className="mt-1 text-[9px] leading-4 text-[#68717d]">{skill.description}</div><button className="tool-button mt-2 w-full" onClick={()=>{dispatchExtensionSkill(extension,skill);setOpen(false);}}><Play size={10}/> Run in AI Edit</button></div>)}</div></div>}
        </article>)}</div>}</div>
  </div></div>;
}
